spring:
  application:
    name: apiGateway
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/netflix
    username: root
    password: admin
server:
  port: 8090